### ISSUE TITLE
How to solve the references between the two SharedPtr？

### ISSUE THREAD

**Issue by pisuto** [RRRadicalEdward/smart_pointers#1]
> class B;
> class A {
> public:
>     weak_ptr<B> b;
>     ~A() { std::cout << "~A " << std::endl; }
> };
> class B {
> public:
>     weak_ptr<A> a;
>     ~B() { std::cout << "~B " << std::endl; }
> };
> 
> 
> int main()
> {
>     shared_ptr<A> spa(new A());
>     shared_ptr<B> spb(new B());
>     spb->a = spa;
>     spa->b = spb;
>     return 0;
> }

The objects cannot be deconstructed correctly...
Do you have any idea?

**Comment by RRRadicalEdward** [comment]
Hey. I did. I just explicitly added the to the weak_ptrs their template params and it works.
class B;
class A {
public:
    std::weak_ptr<B> b;
    ~A() { std::cout << "~A " << std::endl; }
};
class B {
public:
    std::weak_ptr<A> a;
    ~B() { std::cout << "~B " << std::endl; }
};


int main()
{

    Unique_ptr<int> unique(new int);

    std::shared_ptr<A> spa(new A());
    std::shared_ptr<B> spb(new B());
    spb->a = spa;
    spa->b = spb;

    return 0;
}

Also, I checked it by the Valgrin, and there isn't any memory problems. I hope it's actually what you needed.

**Comment by pisuto** [comment]
Sorry, I dont ask clearly.
I use your smart_pointers to test the code. It's below:

```
class B;
class A {
public:
WeakPtr<B> b;
~A() { std::cout << "~A " << std::endl; }
};
class B {
public:
WeakPtr<A> a;
~B() { std::cout << "~B " << std::endl; }
};

int main()
{
SharedPtr<A> spa(new A());
SharedPtr<B> spb(new B());
spb->a = spa;
spa->b = spb;

return 0;
}
```
and the memoy leak happens.

**Comment by RRRadicalEdward** [comment]
Yeah. there is truly a memory leak. Plenty of unit tests couldn't save sometimes. The issues could relay to the Weak class and how it performs all the pointer cast and constructs. I wrote the smart pointers for studying purposes. I haven't been coding in C++ for the last 2 months till today, Would you like to investigate your time to solve the issues?

**Comment by pisuto** [comment]
OK, thank you for your reply. I will try to find a way to solve the problem. Thank you again.

**Comment by pisuto** [comment]
Referring to the answer in [https://stackoverflow.com/questions/5671241/how-does-weak-ptr-work?r=SearchResults](url), the solution is below and just add some code:
```
                void increaseSharedCounter() noexcept
		{
			this->sharedCounter++;
			this->weakCounter++;
		}
                void decreaseSharedCounter() noexcept
		{
			this->sharedCounter--;
			this->weakCounter--;
		}
                bool must_be_deleted() const noexcept {
			return !weakCounter;
		}
```
The code needs to be improved, but the memory leak is gone.
